# Generated by Django 3.1.7 on 2022-05-27 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True, verbose_name='Updated at')),
                ('created_by', models.CharField(blank=True, db_column='created_by', default='', max_length=100, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, db_column='modified_by', default='', max_length=100, null=True, verbose_name='Updated by')),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Album',
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True, verbose_name='Updated at')),
                ('created_by', models.CharField(blank=True, db_column='created_by', default='', max_length=100, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, db_column='modified_by', default='', max_length=100, null=True, verbose_name='Updated by')),
                ('name', models.CharField(db_column='name', max_length=255, verbose_name='Name')),
                ('stage_name', models.CharField(blank=True, db_column='stage_name', max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, db_column='birthday', null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=200, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'Singer',
                'db_table': 'singer',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True, verbose_name='Updated at')),
                ('created_by', models.CharField(blank=True, db_column='created_by', default='', max_length=100, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, db_column='modified_by', default='', max_length=100, null=True, verbose_name='Updated by')),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True, verbose_name='Name')),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.album')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.singer')),
            ],
            options={
                'verbose_name_plural': 'Song',
                'db_table': 'song',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.singer'),
        ),
    ]
