# Generated by Django 3.1.7 on 2022-05-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='singer',
            new_name='singer_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='albums',
            new_name='album_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='singer_id',
        ),
    ]
