# Generated by Django 3.1.7 on 2022-05-27 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220527_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='singer_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='singer_id',
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.singer'),
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.singer'),
        ),
    ]
