# Generated by Django 3.1.7 on 2022-05-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220527_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
    ]
