# Generated by Django 3.1.7 on 2022-05-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_song_singers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='singer',
            new_name='singers',
        ),
    ]
