# Generated by Django 3.1.7 on 2022-06-01 03:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220527_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.PositiveIntegerField(blank=True, db_column='views', default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='album',
            name='singers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='core.singer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='albums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='songs', to='core.album'),
        ),
    ]
