# Generated by Django 3.2.4 on 2022-06-16 09:15
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220601_1001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='singer',
            unique_together={('name', 'stage_name')}, ),
    ]
