# status
DELETE_SUCCESS = 'DELETE SUCCESS'
DATA_IS_NOT_NONE = "DATA_IS_NOT_NONE"

# singer
ERROR_STAGE_NAME_IS_EXISTED = 'ERROR_STAGE_NAME_IS_EXISTED'

# album
ERROR_NAME_IS_EXISTED = "ERROR_NAME_IS_EXISTED"
